# Generated by Django 4.1.5 on 2023-01-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.everestkitchenpa.com%2Fassets%2Fpages%2Fthukpa.html&psig=AOvVaw0UL1EHxuEWkz_B4j6jCj9D&ust=1674828952629000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCIj4pJe25fwCFQAAAAAdAAAAABAE', max_length=500),
        ),
    ]
