# Generated by Django 4.1.5 on 2023-01-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fdribbble.com%2Fshots%2F4187820-404-Food-Not-Found&psig=AOvVaw0UL1EHxuEWkz_B4j6jCj9D&ust=1674828952629000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCIj4pJe25fwCFQAAAAAdAAAAABAJ', max_length=500),
        ),
    ]
